name: copy-file-to-oss
on: 
  push:
    branches:
      - master
jobs:
  copy-file-to-oss:
    name: copy static page file to oss
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: "oss-cn-qingdao.aliyuncs.com"
          access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.ACCESS_KEY_SECRET }}
      - run: ossutil cp ./ oss://codeorder-cn-static-page/ --include "*.html" -fr